# Generated by Django 6.0 on 2025-12-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='blog_title',
        ),
    ]
